export const electronics = [
  {
    id:1,
    name: "AMAZFIT T rex Pro 1.3HD AMOLED",
    rating: "4.5",
    rate: "9999",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/312/312/xif0q/smartwatch/r/7/u/-original-imagpf7nayrqf8vb.jpeg?q=70",
  },
  {
    id:2,
    name: "Fire Bold Talk ultra",
    rating: "4.0",
    rate: "12000",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/312/312/xif0q/smartwatch/r/7/u/-original-imagpf7nayrqf8vb.jpeg?q=70",
  },
  {
    id:3,
    name: "Fire Bold Sonic",
    rating: "4.2",
    rate: "7999",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/312/312/xif0q/smartwatch/r/7/u/-original-imagpf7nayrqf8vb.jpeg?q=70",
  },
  {
    id:4,
    name: "Ambran wise-rome",
    rating: "3.8",
    rate: "2999",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/312/312/xif0q/smartwatch/r/7/u/-original-imagpf7nayrqf8vb.jpeg?q=70",
  },
  {
    id:5,
    name: "noice crew",
    rating: "4.0",
    rate: "4500",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/312/312/xif0q/smartwatch/r/7/u/-original-imagpf7nayrqf8vb.jpeg?q=70",
  },
  {
    id:6,
    name: "Samsong watch 4",
    rating: "4.5",
    rate: "12000",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/312/312/xif0q/smartwatch/r/7/u/-original-imagpf7nayrqf8vb.jpeg?q=70",
  },
];
export const grocery = [
  {
    id:11,
    name: "Rin Detergent bar",
    rating: "1000g",
    rate: "99",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/192/192/l4x2rgw0/washing-bar/u/y/i/-original-imagfpjrng39ummh.jpeg?q=70",
  },
  {
    id:12,
    name: "Fire Bold Talk ultra",
    rating: "4.0",
    rate: "12000",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/192/192/l4x2rgw0/washing-bar/u/y/i/-original-imagfpjrng39ummh.jpeg?q=70",
  },
  {
    id:13,
    name: "Fire Bold Sonic",
    rating: "4.2",
    rate: "7999",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/192/192/ktx9si80/washing-powder/c/1/i/plus-extra-power-jasmine-and-rose-tide-original-imag75zk9zfq9jyt.jpeg?q=70",
  },
  {
    id:14,
    name: "Ambran wise-rome",
    rating: "3.8",
    rate: "2999",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/192/192/ktx9si80/washing-powder/c/1/i/plus-extra-power-jasmine-and-rose-tide-original-imag75zk9zfq9jyt.jpeg?q=70",
  },
  {
    id:15,
    name: "noice crew",
    rating: "4.0",
    rate: "4500",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/192/192/ktrk13k0/liquid-detergent/e/j/k/matic-top-load-surf-excel-original-imag7fhvcgqkteeg.jpeg?q=70",
  },
  {
    id:16,
    name: "Samsong watch 4",
    rating: "4.5",
    rate: "12000",
    cost:0,
    qty:1,
    img: "https://rukminim1.flixcart.com/image/192/192/ktrk13k0/liquid-detergent/e/j/k/matic-top-load-surf-excel-original-imag7fhvcgqkteeg.jpeg?q=70",
  },
];
